include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_const_constructors: true
    prefer_const_constructors_in_immutables: true
    prefer_const_declarations: true
    prefer_const_literals_to_create_immutables: true
    require_trailing_commas: true
    prefer_final_locals: true
    prefer_final_in_for_each: true
    prefer_final_fields: true
    unnecessary_this: false
